services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: cinetrack
      POSTGRES_PASSWORD: cinetrack
      POSTGRES_DB: cinetrack
    ports:
      - "5433:5432"
    volumes:
      - cinetrack_pg:/var/lib/postgresql/data

volumes:
  cinetrack_pg:
